import { Task } from '@/types/task';

// Mock data for demo purposes until Supabase integration
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design TASKMAN UI Components',
    description: 'Create beautiful and responsive UI components for the task management application',
    deadline: new Date('2024-07-20'),
    priority: 'high',
    status: 'in-progress',
    tags: ['Design', 'UI/UX', 'Frontend'],
    isRecurring: false,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-07-14'),
  },
  {
    id: '2',
    title: 'Implement Authentication System',
    description: 'Set up Supabase authentication with JWT tokens',
    deadline: new Date('2024-07-18'),
    priority: 'high',
    status: 'todo',
    tags: ['Backend', 'Auth', 'Security'],
    isRecurring: false,
    createdAt: new Date('2024-07-12'),
    updatedAt: new Date('2024-07-12'),
  },
  {
    id: '3',
    title: 'Daily Standup Meeting',
    description: 'Team sync meeting to discuss progress and blockers',
    deadline: new Date('2024-07-15'),
    priority: 'medium',
    status: 'done',
    tags: ['Meeting', 'Team'],
    isRecurring: true,
    recurringInterval: 'daily',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-14'),
  },
  {
    id: '4',
    title: 'Write API Documentation',
    description: 'Document all REST API endpoints for the task management system',
    deadline: new Date('2024-07-25'),
    priority: 'low',
    status: 'todo',
    tags: ['Documentation', 'API'],
    isRecurring: false,
    createdAt: new Date('2024-07-13'),
    updatedAt: new Date('2024-07-13'),
  },
  {
    id: '5',
    title: 'Code Review Session',
    description: 'Review and provide feedback on recent pull requests',
    deadline: new Date('2024-07-16'),
    priority: 'medium',
    status: 'in-progress',
    tags: ['Review', 'Code Quality'],
    isRecurring: false,
    createdAt: new Date('2024-07-14'),
    updatedAt: new Date('2024-07-14'),
  }
];