// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivjcwwgfguzsjjheyzsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2amN3d2dmZ3V6c2pqaGV5enN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzcyMjAsImV4cCI6MjA2ODA1MzIyMH0.8zemdsvsp12VdoXEqlLzCVOnvrNrquOStRg8PHnUutI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});